### ISSUE TITLE
镜像不是最新的

### ISSUE THREAD

**Issue by zhuwenbing** [Acris/docker-shadowsocks-libev#11]
打扰了！镜像拉下来不是最新的，麻烦您给检查一下，谢谢！
docker pull acrisliu/shadowsocks-libev:latest
docker images
acrisliu/shadowsocks-libev   latest              ee9790bbaa05        3 weeks ago         26.5MB
试了多次都是3周前的。

**Comment by Acris** [comment]
请检查下docker源是否为官方源。

**Comment by zhuwenbing** [comment]
不好意思，是我的问题（忘记之前加速镜像使用了阿里的源），感谢您的回复！
