### ISSUE TITLE
直接使用证书生成的路径可以吗？

### ISSUE THREAD

**Issue by bishiping** [Acris/docker-shadowsocks-libev#12]
我看-e ARGS后面cert和key路径直接选的脚本自动生成证书文件的存放路径，这样子脚本每60天更新过后这个docker会自动使用吗，这样子没什么问题吧？还有就是希望可以添加一下在shadowsocks-win端插件的书写方法，另外mux=0，这样子可以给一个参数设置吗，我这有个软件Quantumult X支持mux=0的ss+v2ray-plugin，无法直接用这个搭建好的。

**Comment by Acris** [comment]
1、我个人使用的是caddy生成的证书，没有测试过挂载外部证书的情况，所以需要自行测试一下。
2、从 https://github.com/shadowsocks/v2ray-plugin/releases 下载Windows版本的v2ray-plugin，解压并重命名为v2ray-plugin.exe，然后放入Shadowsocks.exe相同目录。之后在Shadowsocks windows的编辑服务器界面，插件程序填`v2ray-plugin`，插件选项填你服务端对应的配置，如`tls;host=example.com;path=/v2ray`即可。
3、服务端部署的时候，给v2ray-plugin插件的选项中添加mux=0即可。

**Comment by bishiping** [comment]
好的，谢谢。
