### ISSUE TITLE
要怎样设置才可以使用ipv6呢

### ISSUE THREAD

**Issue by aria001** [Acris/docker-shadowsocks-libev#14]
用test-ipv6.com测试显示没有ipv6地址
已经确认我的主机拥有ipv6地址

**Comment by Acris** [comment]
- 为docker启用IPv6支持: https://docs.docker.com/config/daemon/ipv6/
- <del>启动ss-server时将`SERVER_ADDRS`设置为`::`。</del>
- 启动ss-server时将`SERVER_ADDR`设置为`::0`。

**Comment by zhuwenbing** [comment]
以上实测无效。
1、参数名应为SERVER_ADDR（文档里面参数名也不正确）。
2、参数名正确后确实可以了，但是只会监听IPv6端口，而不会监听IPv4端口。
最后没有去配置SERVER_ADDR参数，而是通过在ARGS参数里面添加 -s ::0 来解决以上问题，亲测有效。

**Comment by aria001** [comment]
> 以上实测无效。
> 1、参数名应为SERVER_ADDR（文档里面参数名也不正确）。
> 2、参数名正确后确实可以了，但是只会监听IPv6端口，而不会监听IPv4端口。
> 最后没有去配置SERVER_ADDR参数，而是通过在ARGS参数里面添加 -s ::0 来解决以上问题，亲测有效。

关于ipv6的支持，实际上docker 20.10.2以上支持了ip6tables，为docker启用ipv6是很简单的，只需要编辑 /etc/docker/daemon.json文件，添加以下内容：
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80",
  "experimental": true,
  "ip6tables": true
}
随后重启docker engine就行了

实际上在ARGS里加上-s参数与使用SERVER_ADDR应当是一样的，本质上都是ss-server的-s参数。事实上我之前也没有发现参数名是错的，也就是说，-s参数应当是使用了默认的0.0.0.0，同样能够正常使用ipv6

**Comment by Acris** [comment]
感谢指正，文档已修复。
