### ISSUE TITLE
problems when work behind Nginx

### ISSUE THREAD

**Issue by aria001** [Acris/docker-shadowsocks-libev#15]
I want to make shadowsocks work behind an Nginx server. So I write an Nginx config file like this
![nginx](https://user-images.githubusercontent.com/17241830/71308315-caa68a00-2435-11ea-9cd9-d3b5b53bcc8a.png)

Then I run shadowsocks by this
![Inkedshadowsocks_LI](https://user-images.githubusercontent.com/17241830/71308386-f6763f80-2436-11ea-8612-583ff3a5a255.jpg)

and I set my windows client like this
![ss配置](https://user-images.githubusercontent.com/17241830/71308348-5cae9280-2436-11ea-8b69-c3aaf9a17dae.png)

But It just not working. Here's nginx access log 
![nginx-status](https://user-images.githubusercontent.com/17241830/71308368-b1eaa400-2436-11ea-9897-b7bda140019f.png)

**Comment by Acris** [comment]
Remove `tls`, `key` and `cert` from your container arguments and try again.

**Comment by Acris** [comment]
Issue closed, feel free to re-open it if needed.
