### ISSUE TITLE
There is no way to make WhatsApp voice calls on version 5.1.7

### ISSUE THREAD

**Issue by ayton** [Acris/docker-shadowsocks-libev#24]
There is no way to make WhatsApp voice calls on version 5.1.7, but when using version "Shadowsocks client without AD" created by TrueNight, based on version 4.8.4 from Google Play, there are no such problems.

Im created example: v2ray-plugin with TLS mode and enable UDP relay.

I would be glad of any information to solve this ...

**Comment by Acris** [comment]
Ref: https://github.com/shadowsocks/shadowsocks-android/issues/2639
