### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)...

### ISSUE THREAD

**Issue by lobstergy** [Acris/docker-shadowsocks-libev#29]
Hi Acris,
Got error massage "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested" when running on my newly created Ampere instance with ubuntu 20.04, is this mean that the docker file doesn't support arm64, could you make it support both amd64 and arm64 or more architectures? Thanks!
P.S. Running on Other amd64 instance with the same ubuntu 20.04 is normal.

P.P.S.:cupinfo
lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian

**Comment by Acris** [comment]
Hi,
Please try again and help test all the functions, especially if v2ray-plugin works properly on arm64 platform, thanks.

**Comment by lobstergy** [comment]
Thank you add support for arm64 architecture in such a snap way, everything runs normal, fully support arm64(v8) server, then parted with client platforms, IOS, Mac, Android and router (Asus-AC88U), I can easily get 150Mbps which max out my 100Mbps Unicom broadband via an Oracle Ampere A1, 2 OCPU instance, max network bandwidth is 1 Gbps/OCPU, 2Gbps network bandwidth. Now, the sky is the limit, huh! :) Thanks again!
