### ISSUE TITLE
有几个问题，麻烦大佬看一下。

### ISSUE THREAD

**Issue by huanauh** [Acris/docker-shadowsocks-libev#3]
1、`-v /home/username/.acme.sh:/root/.acme.sh`后面应该也要有` \`吧。
2、可否增加自定义`fast_open`参数，默认这个参数是打开的，我这边会报错`ERROR: failed to set TCP_FASTOPEN_CONNECT`，而且貌似tcp fastopen在docker里面启用好像没什么作用吧。
综上，我觉得可能用配置文件的形式更灵活一点，启动参数也可以不用这么多。

**Comment by Acris** [comment]
感谢，已修正。
