### ISSUE TITLE
如何填写DNS_ADDRS 走本机默认DNS？

### ISSUE THREAD

**Issue by JusufUs** [Acris/docker-shadowsocks-libev#40]
如何填写DNS_ADDRS走本机默认DNS，而不是填写某一个IP。
如果不写他就会默认走8.8.8.8或1.1.1.1了，是否可以写127.0.0.1，他默认就走系统的DNS？

**Comment by Acris** [comment]
`DNS_ADDRS=127.0.0.1` 即可。
