### ISSUE TITLE
请问握手失败是什么情况呢？

### ISSUE THREAD

**Issue by SawCao** [Acris/docker-shadowsocks-libev#9]
按照readme中步骤，进行操作的，证书也成功生成，但是依然握手失败，无tls启动的话是没问题的。
![image](https://user-images.githubusercontent.com/15178188/65587529-96e3d180-dfb8-11e9-86ae-d67a7a977501.png)

**Comment by Acris** [comment]
请问是用的何种方式？最好是贴一下docker运行的相关命令和参数，注意敏感信息自行打码。

**Comment by SawCao** [comment]
用的docker-compose
参数如下：
![image](https://user-images.githubusercontent.com/15178188/65593665-8edd5f00-dfc3-11e9-930e-b025883046d1.png)
启动日志如下：
![image](https://user-images.githubusercontent.com/15178188/65593700-a3b9f280-dfc3-11e9-9540-8a75dabadb97.png)
错误日志信息如下：
![image](https://user-images.githubusercontent.com/15178188/65593748-b9c7b300-dfc3-11e9-9607-cda45594bbd1.png)

感谢大佬帮忙指正

**Comment by Acris** [comment]
证书使用fullchain试试，即`cert=/root/.acme.sh/yourdomain.com/fullchain.cer`，README上已修正，可以参考。

**Comment by SawCao** [comment]
非常感谢，改成fullchain过后果然没问题了，谢谢大佬指点
